import { Recipe } from '../types';

export const sampleRecipes: Recipe[] = [
  {
    id: '1',
    title: 'Classic Spaghetti Carbonara',
    description: 'A traditional Italian pasta dish made with eggs, cheese, pancetta, and black pepper.',
    servings: 4,
    prepTime: '10 min',
    cookTime: '20 min',
    category: 'Main Course',
    image: 'https://images.unsplash.com/photo-1612874742237-6526221588e3?w=800',
    ingredients: [
      { name: 'Spaghetti', quantity: 400, unit: 'g', scalable: true },
      { name: 'Pancetta', quantity: 200, unit: 'g', scalable: true },
      { name: 'Eggs', quantity: 4, unit: 'whole', scalable: false },
      { name: 'Parmesan cheese', quantity: 100, unit: 'g', scalable: true },
      { name: 'Black pepper', quantity: 1, unit: 'to taste', scalable: false },
      { name: 'Salt', quantity: 1, unit: 'to taste', scalable: false },
    ],
    steps: [
      'Bring a large pot of salted water to boil and cook the spaghetti according to package directions.',
      'While the pasta cooks, dice the pancetta and cook in a large pan over medium heat until crispy.',
      'In a bowl, whisk together eggs and grated Parmesan cheese.',
      'Reserve 1 cup of pasta water, then drain the spaghetti.',
      'Add the hot pasta to the pan with pancetta, remove from heat.',
      'Quickly stir in the egg mixture, adding pasta water as needed to create a creamy sauce.',
      'Season with black pepper and serve immediately with extra Parmesan.',
    ],
    tags: ['Italian', 'Pasta', 'Quick', 'Dinner'],
    isFavorite: true,
    dateAdded: Date.now() - 86400000 * 5,
    isPublic: true,
    authorId: 'user1',
    likeCount: 0,
  },
  {
    id: '2',
    title: 'Chocolate Chip Cookies',
    description: 'Soft and chewy chocolate chip cookies with a perfect golden-brown edge.',
    servings: 24,
    prepTime: '15 min',
    cookTime: '12 min',
    category: 'Dessert',
    image: 'https://images.unsplash.com/photo-1499636136210-6f4ee915583e?w=800',
    ingredients: [
      { name: 'All-purpose flour', quantity: 280, unit: 'g', scalable: true },
      { name: 'Baking soda', quantity: 1, unit: 'tsp', scalable: true },
      { name: 'Salt', quantity: 1, unit: 'tsp', scalable: true },
      { name: 'Butter', quantity: 225, unit: 'g', scalable: true },
      { name: 'Granulated sugar', quantity: 150, unit: 'g', scalable: true },
      { name: 'Brown sugar', quantity: 165, unit: 'g', scalable: true },
      { name: 'Eggs', quantity: 2, unit: 'whole', scalable: false },
      { name: 'Vanilla extract', quantity: 2, unit: 'tsp', scalable: true },
      { name: 'Chocolate chips', quantity: 340, unit: 'g', scalable: true },
    ],
    steps: [
      'Preheat oven to 375°F (190°C).',
      'In a medium bowl, whisk together flour, baking soda, and salt.',
      'In a large bowl, beat softened butter with both sugars until fluffy.',
      'Add eggs one at a time, then vanilla extract.',
      'Gradually mix in the dry ingredients until just combined.',
      'Fold in chocolate chips.',
      'Drop rounded tablespoons of dough onto baking sheets.',
      'Bake for 10-12 minutes until edges are golden.',
      'Cool on baking sheet for 5 minutes, then transfer to a wire rack.',
    ],
    tags: ['Dessert', 'Cookies', 'Baking', 'Sweet'],
    isFavorite: false,
    dateAdded: Date.now() - 86400000 * 3,
    isPublic: true,
    authorId: 'user1',
    likeCount: 0,
  },
  {
    id: '3',
    title: 'Greek Salad',
    description: 'A refreshing Mediterranean salad with tomatoes, cucumbers, olives, and feta cheese.',
    servings: 6,
    prepTime: '15 min',
    cookTime: '0 min',
    category: 'Salad',
    image: 'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=800',
    ingredients: [
      { name: 'Tomatoes', quantity: 4, unit: 'large', scalable: true },
      { name: 'Cucumber', quantity: 1, unit: 'large', scalable: true },
      { name: 'Red onion', quantity: 1, unit: 'medium', scalable: true },
      { name: 'Kalamata olives', quantity: 150, unit: 'g', scalable: true },
      { name: 'Feta cheese', quantity: 200, unit: 'g', scalable: true },
      { name: 'Olive oil', quantity: 80, unit: 'ml', scalable: true },
      { name: 'Red wine vinegar', quantity: 30, unit: 'ml', scalable: true },
      { name: 'Dried oregano', quantity: 1, unit: 'tsp', scalable: true },
      { name: 'Salt and pepper', quantity: 1, unit: 'to taste', scalable: false },
    ],
    steps: [
      'Chop tomatoes into wedges and place in a large bowl.',
      'Dice cucumber and thinly slice red onion.',
      'Add olives and cucumber to the bowl.',
      'Crumble feta cheese over the vegetables.',
      'In a small bowl, whisk together olive oil, vinegar, oregano, salt, and pepper.',
      'Pour dressing over salad and toss gently.',
      'Let sit for 10 minutes before serving to allow flavors to meld.',
    ],
    tags: ['Vegetarian', 'Healthy', 'Mediterranean', 'Quick', 'Salad'],
    isFavorite: true,
    dateAdded: Date.now() - 86400000 * 1,
    isPublic: true,
    authorId: 'user1',
    likeCount: 0,
  },
  {
    id: '4',
    title: 'Chicken Stir-Fry',
    description: 'Quick and healthy chicken stir-fry with colorful vegetables and savory sauce.',
    servings: 4,
    prepTime: '20 min',
    cookTime: '15 min',
    category: 'Main Course',
    image: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?w=800',
    ingredients: [
      { name: 'Chicken breast', quantity: 500, unit: 'g', scalable: true },
      { name: 'Bell peppers', quantity: 2, unit: 'whole', scalable: true },
      { name: 'Broccoli', quantity: 300, unit: 'g', scalable: true },
      { name: 'Soy sauce', quantity: 60, unit: 'ml', scalable: true },
      { name: 'Garlic', quantity: 3, unit: 'cloves', scalable: true },
      { name: 'Ginger', quantity: 2, unit: 'tsp', scalable: true },
      { name: 'Sesame oil', quantity: 2, unit: 'tbsp', scalable: true },
      { name: 'Cornstarch', quantity: 1, unit: 'tbsp', scalable: true },
      { name: 'Rice', quantity: 400, unit: 'g', scalable: true },
    ],
    steps: [
      'Cook rice according to package directions.',
      'Cut chicken into bite-sized pieces and toss with cornstarch.',
      'Chop vegetables into similar-sized pieces.',
      'Heat sesame oil in a large wok or skillet over high heat.',
      'Add chicken and cook until golden, about 5-6 minutes.',
      'Add garlic and ginger, cook for 30 seconds.',
      'Add vegetables and stir-fry for 3-4 minutes.',
      'Pour in soy sauce and toss everything together.',
      'Serve hot over rice.',
    ],
    tags: ['Asian', 'Healthy', 'Quick', 'Dinner', 'Chicken'],
    isFavorite: false,
    dateAdded: Date.now() - 86400000 * 7,
    isPublic: false,
    authorId: 'user1',
    likeCount: 0,
  },
  {
    id: '5',
    title: 'Banana Bread',
    description: 'Moist and delicious banana bread perfect for breakfast or snacking.',
    servings: 10,
    prepTime: '15 min',
    cookTime: '60 min',
    category: 'Baking',
    image: 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=800',
    ingredients: [
      { name: 'Ripe bananas', quantity: 3, unit: 'large', scalable: true },
      { name: 'All-purpose flour', quantity: 280, unit: 'g', scalable: true },
      { name: 'Baking soda', quantity: 1, unit: 'tsp', scalable: true },
      { name: 'Salt', quantity: 0.5, unit: 'tsp', scalable: true },
      { name: 'Butter', quantity: 115, unit: 'g', scalable: true },
      { name: 'Brown sugar', quantity: 200, unit: 'g', scalable: true },
      { name: 'Eggs', quantity: 2, unit: 'whole', scalable: false },
      { name: 'Vanilla extract', quantity: 1, unit: 'tsp', scalable: true },
      { name: 'Walnuts', quantity: 100, unit: 'g', scalable: true },
    ],
    steps: [
      'Preheat oven to 350°F (175°C) and grease a 9x5 inch loaf pan.',
      'In a bowl, mash the ripe bananas until smooth.',
      'In another bowl, whisk together flour, baking soda, and salt.',
      'Melt butter and mix with brown sugar.',
      'Beat in eggs and vanilla extract.',
      'Fold in mashed bananas.',
      'Gently mix in dry ingredients until just combined.',
      'Fold in chopped walnuts if using.',
      'Pour batter into prepared pan.',
      'Bake for 60 minutes or until a toothpick comes out clean.',
      'Cool in pan for 10 minutes, then transfer to a wire rack.',
    ],
    tags: ['Baking', 'Breakfast', 'Sweet', 'Snack'],
    isFavorite: true,
    dateAdded: Date.now() - 86400000 * 10,
    isPublic: true,
    authorId: 'user1',
    likeCount: 0,
  },
];